services:
  
  backend:
    container_name: backend
    build: .
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - API_BASE_PATH=/api
      - DEBUG_LEVEL=debug
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=bestreads
      - DB_PASSWORD=test
      - DB_NAME=bestreads_db
      - DB_SSL_MODE=false

  database:
    container_name: database
    image: postgres:18.1
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_USER=bestreads
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=bestreads_db
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
