services:
  
  bestreads-backend:
    container_name: bestreads-backend
    build: .
    restart: unless-stopped
    depends_on:
      - bestreads-database
    ports:
      - "3000:8080"
    environment:
      - API_PORT=8080
      - API_BASE_PATH=/api
      - DEBUG_LEVEL=debug
      - DB_HOST=bestreads-database
      - DB_PORT=5432
      - DB_USERNAME=bestreads
      - DB_PASSWORD=test
      - DB_NAME=bestreads_db
      - DB_SSL_MODE=false
      - REFRESH_TOKEN_SECRET_KEY=test1
      - ACCESS_TOKEN_SECRET_KEY=test2
      - TOKEN_SECURE_FLAG=false

  bestreads-database:
    container_name: bestreads-database
    image: postgres:18.1
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_USER=bestreads
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=bestreads_db
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
